version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: chatbot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: chatbot_db
      POSTGRES_USER: chatbot_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-chatbot_secure_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - chatbot-network

  # Chatbot Application
  chatbot:
    image: tes4
    container_name: chatbot-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=postgresql://chatbot_user:${POSTGRES_PASSWORD:-chatbot_secure_password}@postgres:5432/chatbot_db
      - GROQ_API_KEY=${GROQ_API_KEY}
    ports:
      - "3000:5000"
    networks:
      - chatbot-network

volumes:
  postgres_data:
    driver: local

networks:
  chatbot-network:
    driver: bridge
